### ISSUE TITLE
Can't embed videos when editing Campaign's updates

### ISSUE THREAD

**Issue by michelesbw** [hypeJunction/hypeEmbed#6]
Hello,
I installed great hypeembed but when I try to embed a video within a campaign's update (edit mode, the update was published previously), as soon as I hit "Embed" after pasting the video's url, the update isn't saved, stays as before.
If of any importance, the videos I tried to embed are:
https://www.youtube.com/watch?v=kb5IJQ0FcLA
and
https://www.youtube.com/watch?v=pReo9yopMCQ&t=605s

Strangely, if I add embed code manually I get 2 different results as below (beta and prod) with same plugins, also same hypescraper version 5.4.0

BETA
![beta](https://user-images.githubusercontent.com/5203511/27547825-7253d552-5a97-11e7-8f08-35708e05ffea.png)

PROD
![prod](https://user-images.githubusercontent.com/5203511/27547838-7bbf2308-5a97-11e7-9204-c4974d91f051.png)

Cheers

**Comment by hypeJunction** [comment]
Can't reproduce. Update to latest version of hypEmbed and hypeScraper.
