### ISSUE TITLE
Not embedding files in correct tab (ie. Campaign description's languages)

### ISSUE THREAD

**Issue by michelesbw** [hypeJunction/hypeEmbed#8]
Hello,
When trying to embed an image in italian description of a crowdfunding campaign, the file gets embedded in english description tab.
English is our default site's language so I guess hypeembed doesn't "see" the actual tab user is writing into.
Cheers

**Comment by hypeJunction** [comment]
Hopefully fixed by https://github.com/sbwtech/sbw_campaigns/commit/04a36ee9299cc0eb41fafe40c1cf875d4e98405f

**Comment by michelesbw** [comment]
Unfortunately not. :S
Still embedding in default site's language tab
